# backend/tancho/config/config.ymlfastapi:
debug: true

databases:
    default:
        ENGINE: 'mongodb'
        DRIVER: 'motor'
        NAME: 'tancho_test_db' # 'tancho_db'
        USER: 'tancho_user'
        PASSWORD: '4dm1n4dm1n'
        HOST: 'mongo'
        PORT: 27017